SET GLOBAL sql_mode='';

CREATE DATABASE IF NOT EXISTS `management`;
CREATE USER IF NOT EXISTS 'PiranhaFish'@'localhost' IDENTIFIED BY 'saasameFTW';
REVOKE ALL PRIVILEGES ON `management`.* FROM 'PiranhaFish'@'localhost';
GRANT SELECT, INSERT, UPDATE, DROP, LOCK TABLES ON `management`.* TO 'PiranhaFish'@'localhost';
FLUSH PRIVILEGES;

USE `management`;
ALTER TABLE `_CLOUD_MGMT` ADD `_CLOUD_TYPE` INT( 4 ) NOT NULL DEFAULT '1' AFTER `_TIMESTAMP`;
ALTER TABLE `_SERVER` CHANGE COLUMN `_HOST_UUID` `_HOST_UUID` TEXT CHARACTER SET 'utf8' NOT NULL;
ALTER TABLE `_SERVER` CHANGE `_HOST_NAME` `_HOST_NAME` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_SERVICE` ADD `_IMAGE_ID` TEXT NULL DEFAULT NULL AFTER `_NOVA_VM_UUID`;
ALTER TABLE `_SERVICE` ADD `_TASK_ID` TEXT NULL DEFAULT NULL AFTER `_IMAGE_ID`;
ALTER TABLE `_SERVICE` CHANGE `_WINPE_JOB` `_JOBS_JSON` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_SERVICE` CHANGE `_SGROUP_UUID` `_SGROUP_UUID` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_SERVICE` CHANGE `_IMAGE_ID` `_IMAGE_ID` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `_SERVICE` CHANGE `_TASK_ID` `_TASK_ID` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `_SERVICE` CHANGE `_NETWORK_UUID` `_NETWORK_UUID` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_SERVICE` CHANGE `_NOVA_VM_UUID` `_NOVA_VM_UUID` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_CLOUD_DISK` CHANGE `_OPEN_DISK_UUID` `_OPEN_DISK_UUID` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_CLOUD_DISK` CHANGE `_OPEN_SERV_UUID` `_OPEN_SERV_UUID` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_CLOUD_DISK` CHANGE `_OPEN_DISK_ID` `_OPEN_DISK_ID` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_REPLICA_DISK` CHANGE `_OPEN_DISK` `_OPEN_DISK` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE `_SERVICE_DISK` CHANGE `_OPEN_DISK` `_OPEN_DISK` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_SERVICE_DISK` CHANGE `_SNAP_UUID` `_SNAP_UUID` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `_REPLICA_SNAP` ADD `_TRANSPORT_DATA` BIGINT( 15 ) NOT NULL DEFAULT '0' AFTER `_LOADER_DATA` ;
ALTER TABLE `_REPLICA_SNAP` ADD `_CBT_INFO` TEXT NOT NULL AFTER `_SNAP_OPEN` ;
ALTER TABLE `_REPLICA_SNAP` ADD `_SNAP_OPTIONS` TEXT NOT NULL AFTER `_CBT_INFO` ;
ALTER TABLE `_JOBS_HISTORY` ADD `_HIST_TIME` VARCHAR( 36 ) NOT NULL DEFAULT '1970-01-01 00:00:00' AFTER `_HIST_JSON` ;
ALTER TABLE `_JOBS_HISTORY` ADD `_IS_DISPLAY` VARCHAR( 1 ) NOT NULL DEFAULT 'Y' AFTER `_SYNC_TIME` ;
ALTER TABLE `_JOBS_HISTORY` ADD INDEX ( `_HIST_TIME` ) ;
ALTER TABLE `_JOBS_HISTORY` ADD INDEX ( `_SYNC_TIME` ) ;

INSERT INTO `_SYS_RESTFUL_REF` (`_URI_NAME`, `_REF_NAME`, `_STATUS`) SELECT * FROM (SELECT 'AliyunWebServices', '_AliyunWebServices.php', 'Y') AS tmp WHERE NOT EXISTS (SELECT * FROM `_SYS_RESTFUL_REF` WHERE `_URI_NAME` = 'AliyunWebServices');
INSERT INTO `_SYS_RESTFUL_REF` (`_URI_NAME`, `_REF_NAME`, `_STATUS`) SELECT * FROM (SELECT 'CtyunWebServices', '_CtyunWebServices.php', 'Y') AS tmp WHERE NOT EXISTS (SELECT * FROM `_SYS_RESTFUL_REF` WHERE `_URI_NAME` = 'CtyunWebServices');
INSERT INTO `_SYS_RESTFUL_REF` (`_URI_NAME`, `_REF_NAME`, `_STATUS`) SELECT * FROM (SELECT 'TencentWebServices', '_TencentWebServices.php', 'Y') AS tmp WHERE NOT EXISTS (SELECT * FROM `_SYS_RESTFUL_REF` WHERE `_URI_NAME` = 'TencentWebServices');
INSERT INTO `_SYS_RESTFUL_REF` (`_URI_NAME`, `_REF_NAME`, `_STATUS`) SELECT * FROM (SELECT 'VMWareWebServices', '_VMWareWebServices.php', 'Y') AS tmp WHERE NOT EXISTS (SELECT * FROM `_SYS_RESTFUL_REF` WHERE `_URI_NAME` = 'VMWareWebServices');
INSERT INTO `_SYS_CLOUD_TYPE` (`_CLOUD_TYPE`) SELECT * FROM (SELECT 'Ctyun') AS tmp WHERE NOT EXISTS (SELECT * FROM `_SYS_CLOUD_TYPE` WHERE `_CLOUD_TYPE` = 'Ctyun');
INSERT INTO `_SYS_CLOUD_TYPE` (`_CLOUD_TYPE`) SELECT * FROM (SELECT 'Tencent') AS tmp WHERE NOT EXISTS (SELECT * FROM `_SYS_CLOUD_TYPE` WHERE `_CLOUD_TYPE` = 'Tencent');
INSERT INTO `_SYS_CLOUD_TYPE` (`_CLOUD_TYPE`) SELECT * FROM (SELECT 'VMWare') AS tmp WHERE NOT EXISTS (SELECT * FROM `_SYS_CLOUD_TYPE` WHERE `_CLOUD_TYPE` = 'VMWare');

CREATE TABLE IF NOT EXISTS `_SERVICE_PLAN` (
  `_ID` int(5) NOT NULL AUTO_INCREMENT,
  `_ACCT_UUID` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `_REGN_UUID` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `_REPL_UUID` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `_PLAN_UUID` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `_PLAN_JSON` text COLLATE utf8_unicode_ci NOT NULL,
  `_TIMESTAMP` datetime NOT NULL,
  `_STATUS` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;