/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef launcher_service_H
#define launcher_service_H

#include <thrift/transport/TBufferTransports.h>
#include <thrift/stdcxx.h>
namespace apache { namespace thrift { namespace async {
class TAsyncChannel;
}}}
#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TAsyncDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "saasame_types.h"
#include "service_proxy.h"

namespace saasame { namespace transport {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class launcher_serviceIf : virtual public service_proxyIf {
 public:
  virtual ~launcher_serviceIf() {}
  virtual void create_job_ex(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id, const create_job_detail& create_job) = 0;
  virtual void create_job(launcher_job_detail& _return, const std::string& session_id, const create_job_detail& create_job) = 0;
  virtual void get_job(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id) = 0;
  virtual bool interrupt_job(const std::string& session_id, const std::string& job_id) = 0;
  virtual bool resume_job(const std::string& session_id, const std::string& job_id) = 0;
  virtual bool update_job(const std::string& session_id, const std::string& job_id, const create_job_detail& job) = 0;
  virtual bool remove_job(const std::string& session_id, const std::string& job_id) = 0;
  virtual void list_jobs(std::vector<launcher_job_detail> & _return, const std::string& session_id) = 0;
  virtual void terminate(const std::string& session_id) = 0;
  virtual bool running_job(const std::string& session_id, const std::string& job_id) = 0;
  virtual bool verify_management(const std::string& management, const int32_t port, const bool is_ssl) = 0;
  virtual bool unregister(const std::string& session) = 0;
};

class launcher_serviceIfFactory : virtual public service_proxyIfFactory {
 public:
  typedef launcher_serviceIf Handler;

  virtual ~launcher_serviceIfFactory() {}

  virtual launcher_serviceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(common_serviceIf* /* handler */) = 0;
};

class launcher_serviceIfSingletonFactory : virtual public launcher_serviceIfFactory {
 public:
  launcher_serviceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<launcher_serviceIf>& iface) : iface_(iface) {}
  virtual ~launcher_serviceIfSingletonFactory() {}

  virtual launcher_serviceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(common_serviceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<launcher_serviceIf> iface_;
};

class launcher_serviceNull : virtual public launcher_serviceIf , virtual public service_proxyNull {
 public:
  virtual ~launcher_serviceNull() {}
  void create_job_ex(launcher_job_detail& /* _return */, const std::string& /* session_id */, const std::string& /* job_id */, const create_job_detail& /* create_job */) {
    return;
  }
  void create_job(launcher_job_detail& /* _return */, const std::string& /* session_id */, const create_job_detail& /* create_job */) {
    return;
  }
  void get_job(launcher_job_detail& /* _return */, const std::string& /* session_id */, const std::string& /* job_id */) {
    return;
  }
  bool interrupt_job(const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return _return;
  }
  bool resume_job(const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return _return;
  }
  bool update_job(const std::string& /* session_id */, const std::string& /* job_id */, const create_job_detail& /* job */) {
    bool _return = false;
    return _return;
  }
  bool remove_job(const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return _return;
  }
  void list_jobs(std::vector<launcher_job_detail> & /* _return */, const std::string& /* session_id */) {
    return;
  }
  void terminate(const std::string& /* session_id */) {
    return;
  }
  bool running_job(const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return _return;
  }
  bool verify_management(const std::string& /* management */, const int32_t /* port */, const bool /* is_ssl */) {
    bool _return = false;
    return _return;
  }
  bool unregister(const std::string& /* session */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _launcher_service_create_job_ex_args__isset {
  _launcher_service_create_job_ex_args__isset() : session_id(false), job_id(false), create_job(false) {}
  bool session_id :1;
  bool job_id :1;
  bool create_job :1;
} _launcher_service_create_job_ex_args__isset;

class launcher_service_create_job_ex_args {
 public:

  launcher_service_create_job_ex_args(const launcher_service_create_job_ex_args&);
  launcher_service_create_job_ex_args& operator=(const launcher_service_create_job_ex_args&);
  launcher_service_create_job_ex_args() : session_id(), job_id() {
  }

  virtual ~launcher_service_create_job_ex_args() throw();
  std::string session_id;
  std::string job_id;
  create_job_detail create_job;

  _launcher_service_create_job_ex_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_job_id(const std::string& val);

  void __set_create_job(const create_job_detail& val);

  bool operator == (const launcher_service_create_job_ex_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(job_id == rhs.job_id))
      return false;
    if (!(create_job == rhs.create_job))
      return false;
    return true;
  }
  bool operator != (const launcher_service_create_job_ex_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_create_job_ex_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_create_job_ex_pargs {
 public:


  virtual ~launcher_service_create_job_ex_pargs() throw();
  const std::string* session_id;
  const std::string* job_id;
  const create_job_detail* create_job;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_create_job_ex_result__isset {
  _launcher_service_create_job_ex_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_create_job_ex_result__isset;

class launcher_service_create_job_ex_result {
 public:

  launcher_service_create_job_ex_result(const launcher_service_create_job_ex_result&);
  launcher_service_create_job_ex_result& operator=(const launcher_service_create_job_ex_result&);
  launcher_service_create_job_ex_result() {
  }

  virtual ~launcher_service_create_job_ex_result() throw();
  launcher_job_detail success;
  invalid_operation ouch;

  _launcher_service_create_job_ex_result__isset __isset;

  void __set_success(const launcher_job_detail& val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_create_job_ex_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_create_job_ex_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_create_job_ex_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_create_job_ex_presult__isset {
  _launcher_service_create_job_ex_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_create_job_ex_presult__isset;

class launcher_service_create_job_ex_presult {
 public:


  virtual ~launcher_service_create_job_ex_presult() throw();
  launcher_job_detail* success;
  invalid_operation ouch;

  _launcher_service_create_job_ex_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_create_job_args__isset {
  _launcher_service_create_job_args__isset() : session_id(false), create_job(false) {}
  bool session_id :1;
  bool create_job :1;
} _launcher_service_create_job_args__isset;

class launcher_service_create_job_args {
 public:

  launcher_service_create_job_args(const launcher_service_create_job_args&);
  launcher_service_create_job_args& operator=(const launcher_service_create_job_args&);
  launcher_service_create_job_args() : session_id() {
  }

  virtual ~launcher_service_create_job_args() throw();
  std::string session_id;
  create_job_detail create_job;

  _launcher_service_create_job_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_create_job(const create_job_detail& val);

  bool operator == (const launcher_service_create_job_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(create_job == rhs.create_job))
      return false;
    return true;
  }
  bool operator != (const launcher_service_create_job_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_create_job_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_create_job_pargs {
 public:


  virtual ~launcher_service_create_job_pargs() throw();
  const std::string* session_id;
  const create_job_detail* create_job;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_create_job_result__isset {
  _launcher_service_create_job_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_create_job_result__isset;

class launcher_service_create_job_result {
 public:

  launcher_service_create_job_result(const launcher_service_create_job_result&);
  launcher_service_create_job_result& operator=(const launcher_service_create_job_result&);
  launcher_service_create_job_result() {
  }

  virtual ~launcher_service_create_job_result() throw();
  launcher_job_detail success;
  invalid_operation ouch;

  _launcher_service_create_job_result__isset __isset;

  void __set_success(const launcher_job_detail& val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_create_job_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_create_job_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_create_job_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_create_job_presult__isset {
  _launcher_service_create_job_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_create_job_presult__isset;

class launcher_service_create_job_presult {
 public:


  virtual ~launcher_service_create_job_presult() throw();
  launcher_job_detail* success;
  invalid_operation ouch;

  _launcher_service_create_job_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_get_job_args__isset {
  _launcher_service_get_job_args__isset() : session_id(false), job_id(false) {}
  bool session_id :1;
  bool job_id :1;
} _launcher_service_get_job_args__isset;

class launcher_service_get_job_args {
 public:

  launcher_service_get_job_args(const launcher_service_get_job_args&);
  launcher_service_get_job_args& operator=(const launcher_service_get_job_args&);
  launcher_service_get_job_args() : session_id(), job_id() {
  }

  virtual ~launcher_service_get_job_args() throw();
  std::string session_id;
  std::string job_id;

  _launcher_service_get_job_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_job_id(const std::string& val);

  bool operator == (const launcher_service_get_job_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(job_id == rhs.job_id))
      return false;
    return true;
  }
  bool operator != (const launcher_service_get_job_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_get_job_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_get_job_pargs {
 public:


  virtual ~launcher_service_get_job_pargs() throw();
  const std::string* session_id;
  const std::string* job_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_get_job_result__isset {
  _launcher_service_get_job_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_get_job_result__isset;

class launcher_service_get_job_result {
 public:

  launcher_service_get_job_result(const launcher_service_get_job_result&);
  launcher_service_get_job_result& operator=(const launcher_service_get_job_result&);
  launcher_service_get_job_result() {
  }

  virtual ~launcher_service_get_job_result() throw();
  launcher_job_detail success;
  invalid_operation ouch;

  _launcher_service_get_job_result__isset __isset;

  void __set_success(const launcher_job_detail& val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_get_job_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_get_job_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_get_job_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_get_job_presult__isset {
  _launcher_service_get_job_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_get_job_presult__isset;

class launcher_service_get_job_presult {
 public:


  virtual ~launcher_service_get_job_presult() throw();
  launcher_job_detail* success;
  invalid_operation ouch;

  _launcher_service_get_job_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_interrupt_job_args__isset {
  _launcher_service_interrupt_job_args__isset() : session_id(false), job_id(false) {}
  bool session_id :1;
  bool job_id :1;
} _launcher_service_interrupt_job_args__isset;

class launcher_service_interrupt_job_args {
 public:

  launcher_service_interrupt_job_args(const launcher_service_interrupt_job_args&);
  launcher_service_interrupt_job_args& operator=(const launcher_service_interrupt_job_args&);
  launcher_service_interrupt_job_args() : session_id(), job_id() {
  }

  virtual ~launcher_service_interrupt_job_args() throw();
  std::string session_id;
  std::string job_id;

  _launcher_service_interrupt_job_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_job_id(const std::string& val);

  bool operator == (const launcher_service_interrupt_job_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(job_id == rhs.job_id))
      return false;
    return true;
  }
  bool operator != (const launcher_service_interrupt_job_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_interrupt_job_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_interrupt_job_pargs {
 public:


  virtual ~launcher_service_interrupt_job_pargs() throw();
  const std::string* session_id;
  const std::string* job_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_interrupt_job_result__isset {
  _launcher_service_interrupt_job_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_interrupt_job_result__isset;

class launcher_service_interrupt_job_result {
 public:

  launcher_service_interrupt_job_result(const launcher_service_interrupt_job_result&);
  launcher_service_interrupt_job_result& operator=(const launcher_service_interrupt_job_result&);
  launcher_service_interrupt_job_result() : success(0) {
  }

  virtual ~launcher_service_interrupt_job_result() throw();
  bool success;
  invalid_operation ouch;

  _launcher_service_interrupt_job_result__isset __isset;

  void __set_success(const bool val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_interrupt_job_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_interrupt_job_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_interrupt_job_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_interrupt_job_presult__isset {
  _launcher_service_interrupt_job_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_interrupt_job_presult__isset;

class launcher_service_interrupt_job_presult {
 public:


  virtual ~launcher_service_interrupt_job_presult() throw();
  bool* success;
  invalid_operation ouch;

  _launcher_service_interrupt_job_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_resume_job_args__isset {
  _launcher_service_resume_job_args__isset() : session_id(false), job_id(false) {}
  bool session_id :1;
  bool job_id :1;
} _launcher_service_resume_job_args__isset;

class launcher_service_resume_job_args {
 public:

  launcher_service_resume_job_args(const launcher_service_resume_job_args&);
  launcher_service_resume_job_args& operator=(const launcher_service_resume_job_args&);
  launcher_service_resume_job_args() : session_id(), job_id() {
  }

  virtual ~launcher_service_resume_job_args() throw();
  std::string session_id;
  std::string job_id;

  _launcher_service_resume_job_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_job_id(const std::string& val);

  bool operator == (const launcher_service_resume_job_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(job_id == rhs.job_id))
      return false;
    return true;
  }
  bool operator != (const launcher_service_resume_job_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_resume_job_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_resume_job_pargs {
 public:


  virtual ~launcher_service_resume_job_pargs() throw();
  const std::string* session_id;
  const std::string* job_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_resume_job_result__isset {
  _launcher_service_resume_job_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_resume_job_result__isset;

class launcher_service_resume_job_result {
 public:

  launcher_service_resume_job_result(const launcher_service_resume_job_result&);
  launcher_service_resume_job_result& operator=(const launcher_service_resume_job_result&);
  launcher_service_resume_job_result() : success(0) {
  }

  virtual ~launcher_service_resume_job_result() throw();
  bool success;
  invalid_operation ouch;

  _launcher_service_resume_job_result__isset __isset;

  void __set_success(const bool val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_resume_job_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_resume_job_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_resume_job_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_resume_job_presult__isset {
  _launcher_service_resume_job_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_resume_job_presult__isset;

class launcher_service_resume_job_presult {
 public:


  virtual ~launcher_service_resume_job_presult() throw();
  bool* success;
  invalid_operation ouch;

  _launcher_service_resume_job_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_update_job_args__isset {
  _launcher_service_update_job_args__isset() : session_id(false), job_id(false), job(false) {}
  bool session_id :1;
  bool job_id :1;
  bool job :1;
} _launcher_service_update_job_args__isset;

class launcher_service_update_job_args {
 public:

  launcher_service_update_job_args(const launcher_service_update_job_args&);
  launcher_service_update_job_args& operator=(const launcher_service_update_job_args&);
  launcher_service_update_job_args() : session_id(), job_id() {
  }

  virtual ~launcher_service_update_job_args() throw();
  std::string session_id;
  std::string job_id;
  create_job_detail job;

  _launcher_service_update_job_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_job_id(const std::string& val);

  void __set_job(const create_job_detail& val);

  bool operator == (const launcher_service_update_job_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(job_id == rhs.job_id))
      return false;
    if (!(job == rhs.job))
      return false;
    return true;
  }
  bool operator != (const launcher_service_update_job_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_update_job_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_update_job_pargs {
 public:


  virtual ~launcher_service_update_job_pargs() throw();
  const std::string* session_id;
  const std::string* job_id;
  const create_job_detail* job;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_update_job_result__isset {
  _launcher_service_update_job_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_update_job_result__isset;

class launcher_service_update_job_result {
 public:

  launcher_service_update_job_result(const launcher_service_update_job_result&);
  launcher_service_update_job_result& operator=(const launcher_service_update_job_result&);
  launcher_service_update_job_result() : success(0) {
  }

  virtual ~launcher_service_update_job_result() throw();
  bool success;
  invalid_operation ouch;

  _launcher_service_update_job_result__isset __isset;

  void __set_success(const bool val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_update_job_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_update_job_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_update_job_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_update_job_presult__isset {
  _launcher_service_update_job_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_update_job_presult__isset;

class launcher_service_update_job_presult {
 public:


  virtual ~launcher_service_update_job_presult() throw();
  bool* success;
  invalid_operation ouch;

  _launcher_service_update_job_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_remove_job_args__isset {
  _launcher_service_remove_job_args__isset() : session_id(false), job_id(false) {}
  bool session_id :1;
  bool job_id :1;
} _launcher_service_remove_job_args__isset;

class launcher_service_remove_job_args {
 public:

  launcher_service_remove_job_args(const launcher_service_remove_job_args&);
  launcher_service_remove_job_args& operator=(const launcher_service_remove_job_args&);
  launcher_service_remove_job_args() : session_id(), job_id() {
  }

  virtual ~launcher_service_remove_job_args() throw();
  std::string session_id;
  std::string job_id;

  _launcher_service_remove_job_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_job_id(const std::string& val);

  bool operator == (const launcher_service_remove_job_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(job_id == rhs.job_id))
      return false;
    return true;
  }
  bool operator != (const launcher_service_remove_job_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_remove_job_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_remove_job_pargs {
 public:


  virtual ~launcher_service_remove_job_pargs() throw();
  const std::string* session_id;
  const std::string* job_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_remove_job_result__isset {
  _launcher_service_remove_job_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_remove_job_result__isset;

class launcher_service_remove_job_result {
 public:

  launcher_service_remove_job_result(const launcher_service_remove_job_result&);
  launcher_service_remove_job_result& operator=(const launcher_service_remove_job_result&);
  launcher_service_remove_job_result() : success(0) {
  }

  virtual ~launcher_service_remove_job_result() throw();
  bool success;
  invalid_operation ouch;

  _launcher_service_remove_job_result__isset __isset;

  void __set_success(const bool val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_remove_job_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_remove_job_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_remove_job_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_remove_job_presult__isset {
  _launcher_service_remove_job_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_remove_job_presult__isset;

class launcher_service_remove_job_presult {
 public:


  virtual ~launcher_service_remove_job_presult() throw();
  bool* success;
  invalid_operation ouch;

  _launcher_service_remove_job_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_list_jobs_args__isset {
  _launcher_service_list_jobs_args__isset() : session_id(false) {}
  bool session_id :1;
} _launcher_service_list_jobs_args__isset;

class launcher_service_list_jobs_args {
 public:

  launcher_service_list_jobs_args(const launcher_service_list_jobs_args&);
  launcher_service_list_jobs_args& operator=(const launcher_service_list_jobs_args&);
  launcher_service_list_jobs_args() : session_id() {
  }

  virtual ~launcher_service_list_jobs_args() throw();
  std::string session_id;

  _launcher_service_list_jobs_args__isset __isset;

  void __set_session_id(const std::string& val);

  bool operator == (const launcher_service_list_jobs_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    return true;
  }
  bool operator != (const launcher_service_list_jobs_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_list_jobs_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_list_jobs_pargs {
 public:


  virtual ~launcher_service_list_jobs_pargs() throw();
  const std::string* session_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_list_jobs_result__isset {
  _launcher_service_list_jobs_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_list_jobs_result__isset;

class launcher_service_list_jobs_result {
 public:

  launcher_service_list_jobs_result(const launcher_service_list_jobs_result&);
  launcher_service_list_jobs_result& operator=(const launcher_service_list_jobs_result&);
  launcher_service_list_jobs_result() {
  }

  virtual ~launcher_service_list_jobs_result() throw();
  std::vector<launcher_job_detail>  success;
  invalid_operation ouch;

  _launcher_service_list_jobs_result__isset __isset;

  void __set_success(const std::vector<launcher_job_detail> & val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_list_jobs_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_list_jobs_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_list_jobs_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_list_jobs_presult__isset {
  _launcher_service_list_jobs_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_list_jobs_presult__isset;

class launcher_service_list_jobs_presult {
 public:


  virtual ~launcher_service_list_jobs_presult() throw();
  std::vector<launcher_job_detail> * success;
  invalid_operation ouch;

  _launcher_service_list_jobs_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_terminate_args__isset {
  _launcher_service_terminate_args__isset() : session_id(false) {}
  bool session_id :1;
} _launcher_service_terminate_args__isset;

class launcher_service_terminate_args {
 public:

  launcher_service_terminate_args(const launcher_service_terminate_args&);
  launcher_service_terminate_args& operator=(const launcher_service_terminate_args&);
  launcher_service_terminate_args() : session_id() {
  }

  virtual ~launcher_service_terminate_args() throw();
  std::string session_id;

  _launcher_service_terminate_args__isset __isset;

  void __set_session_id(const std::string& val);

  bool operator == (const launcher_service_terminate_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    return true;
  }
  bool operator != (const launcher_service_terminate_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_terminate_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_terminate_pargs {
 public:


  virtual ~launcher_service_terminate_pargs() throw();
  const std::string* session_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_terminate_result {
 public:

  launcher_service_terminate_result(const launcher_service_terminate_result&);
  launcher_service_terminate_result& operator=(const launcher_service_terminate_result&);
  launcher_service_terminate_result() {
  }

  virtual ~launcher_service_terminate_result() throw();

  bool operator == (const launcher_service_terminate_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const launcher_service_terminate_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_terminate_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_terminate_presult {
 public:


  virtual ~launcher_service_terminate_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_running_job_args__isset {
  _launcher_service_running_job_args__isset() : session_id(false), job_id(false) {}
  bool session_id :1;
  bool job_id :1;
} _launcher_service_running_job_args__isset;

class launcher_service_running_job_args {
 public:

  launcher_service_running_job_args(const launcher_service_running_job_args&);
  launcher_service_running_job_args& operator=(const launcher_service_running_job_args&);
  launcher_service_running_job_args() : session_id(), job_id() {
  }

  virtual ~launcher_service_running_job_args() throw();
  std::string session_id;
  std::string job_id;

  _launcher_service_running_job_args__isset __isset;

  void __set_session_id(const std::string& val);

  void __set_job_id(const std::string& val);

  bool operator == (const launcher_service_running_job_args & rhs) const
  {
    if (!(session_id == rhs.session_id))
      return false;
    if (!(job_id == rhs.job_id))
      return false;
    return true;
  }
  bool operator != (const launcher_service_running_job_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_running_job_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_running_job_pargs {
 public:


  virtual ~launcher_service_running_job_pargs() throw();
  const std::string* session_id;
  const std::string* job_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_running_job_result__isset {
  _launcher_service_running_job_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_running_job_result__isset;

class launcher_service_running_job_result {
 public:

  launcher_service_running_job_result(const launcher_service_running_job_result&);
  launcher_service_running_job_result& operator=(const launcher_service_running_job_result&);
  launcher_service_running_job_result() : success(0) {
  }

  virtual ~launcher_service_running_job_result() throw();
  bool success;
  invalid_operation ouch;

  _launcher_service_running_job_result__isset __isset;

  void __set_success(const bool val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_running_job_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_running_job_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_running_job_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_running_job_presult__isset {
  _launcher_service_running_job_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_running_job_presult__isset;

class launcher_service_running_job_presult {
 public:


  virtual ~launcher_service_running_job_presult() throw();
  bool* success;
  invalid_operation ouch;

  _launcher_service_running_job_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_verify_management_args__isset {
  _launcher_service_verify_management_args__isset() : management(false), port(false), is_ssl(false) {}
  bool management :1;
  bool port :1;
  bool is_ssl :1;
} _launcher_service_verify_management_args__isset;

class launcher_service_verify_management_args {
 public:

  launcher_service_verify_management_args(const launcher_service_verify_management_args&);
  launcher_service_verify_management_args& operator=(const launcher_service_verify_management_args&);
  launcher_service_verify_management_args() : management(), port(0), is_ssl(0) {
  }

  virtual ~launcher_service_verify_management_args() throw();
  std::string management;
  int32_t port;
  bool is_ssl;

  _launcher_service_verify_management_args__isset __isset;

  void __set_management(const std::string& val);

  void __set_port(const int32_t val);

  void __set_is_ssl(const bool val);

  bool operator == (const launcher_service_verify_management_args & rhs) const
  {
    if (!(management == rhs.management))
      return false;
    if (!(port == rhs.port))
      return false;
    if (!(is_ssl == rhs.is_ssl))
      return false;
    return true;
  }
  bool operator != (const launcher_service_verify_management_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_verify_management_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_verify_management_pargs {
 public:


  virtual ~launcher_service_verify_management_pargs() throw();
  const std::string* management;
  const int32_t* port;
  const bool* is_ssl;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_verify_management_result__isset {
  _launcher_service_verify_management_result__isset() : success(false) {}
  bool success :1;
} _launcher_service_verify_management_result__isset;

class launcher_service_verify_management_result {
 public:

  launcher_service_verify_management_result(const launcher_service_verify_management_result&);
  launcher_service_verify_management_result& operator=(const launcher_service_verify_management_result&);
  launcher_service_verify_management_result() : success(0) {
  }

  virtual ~launcher_service_verify_management_result() throw();
  bool success;

  _launcher_service_verify_management_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const launcher_service_verify_management_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const launcher_service_verify_management_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_verify_management_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_verify_management_presult__isset {
  _launcher_service_verify_management_presult__isset() : success(false) {}
  bool success :1;
} _launcher_service_verify_management_presult__isset;

class launcher_service_verify_management_presult {
 public:


  virtual ~launcher_service_verify_management_presult() throw();
  bool* success;

  _launcher_service_verify_management_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_unregister_args__isset {
  _launcher_service_unregister_args__isset() : session(false) {}
  bool session :1;
} _launcher_service_unregister_args__isset;

class launcher_service_unregister_args {
 public:

  launcher_service_unregister_args(const launcher_service_unregister_args&);
  launcher_service_unregister_args& operator=(const launcher_service_unregister_args&);
  launcher_service_unregister_args() : session() {
  }

  virtual ~launcher_service_unregister_args() throw();
  std::string session;

  _launcher_service_unregister_args__isset __isset;

  void __set_session(const std::string& val);

  bool operator == (const launcher_service_unregister_args & rhs) const
  {
    if (!(session == rhs.session))
      return false;
    return true;
  }
  bool operator != (const launcher_service_unregister_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_unregister_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class launcher_service_unregister_pargs {
 public:


  virtual ~launcher_service_unregister_pargs() throw();
  const std::string* session;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_unregister_result__isset {
  _launcher_service_unregister_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_unregister_result__isset;

class launcher_service_unregister_result {
 public:

  launcher_service_unregister_result(const launcher_service_unregister_result&);
  launcher_service_unregister_result& operator=(const launcher_service_unregister_result&);
  launcher_service_unregister_result() : success(0) {
  }

  virtual ~launcher_service_unregister_result() throw();
  bool success;
  invalid_operation ouch;

  _launcher_service_unregister_result__isset __isset;

  void __set_success(const bool val);

  void __set_ouch(const invalid_operation& val);

  bool operator == (const launcher_service_unregister_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const launcher_service_unregister_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const launcher_service_unregister_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _launcher_service_unregister_presult__isset {
  _launcher_service_unregister_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _launcher_service_unregister_presult__isset;

class launcher_service_unregister_presult {
 public:


  virtual ~launcher_service_unregister_presult() throw();
  bool* success;
  invalid_operation ouch;

  _launcher_service_unregister_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class launcher_serviceClient : virtual public launcher_serviceIf, public service_proxyClient {
 public:
  launcher_serviceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    service_proxyClient(prot, prot) {}
  launcher_serviceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    service_proxyClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void create_job_ex(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id, const create_job_detail& create_job);
  void send_create_job_ex(const std::string& session_id, const std::string& job_id, const create_job_detail& create_job);
  void recv_create_job_ex(launcher_job_detail& _return);
  void create_job(launcher_job_detail& _return, const std::string& session_id, const create_job_detail& create_job);
  void send_create_job(const std::string& session_id, const create_job_detail& create_job);
  void recv_create_job(launcher_job_detail& _return);
  void get_job(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id);
  void send_get_job(const std::string& session_id, const std::string& job_id);
  void recv_get_job(launcher_job_detail& _return);
  bool interrupt_job(const std::string& session_id, const std::string& job_id);
  void send_interrupt_job(const std::string& session_id, const std::string& job_id);
  bool recv_interrupt_job();
  bool resume_job(const std::string& session_id, const std::string& job_id);
  void send_resume_job(const std::string& session_id, const std::string& job_id);
  bool recv_resume_job();
  bool update_job(const std::string& session_id, const std::string& job_id, const create_job_detail& job);
  void send_update_job(const std::string& session_id, const std::string& job_id, const create_job_detail& job);
  bool recv_update_job();
  bool remove_job(const std::string& session_id, const std::string& job_id);
  void send_remove_job(const std::string& session_id, const std::string& job_id);
  bool recv_remove_job();
  void list_jobs(std::vector<launcher_job_detail> & _return, const std::string& session_id);
  void send_list_jobs(const std::string& session_id);
  void recv_list_jobs(std::vector<launcher_job_detail> & _return);
  void terminate(const std::string& session_id);
  void send_terminate(const std::string& session_id);
  void recv_terminate();
  bool running_job(const std::string& session_id, const std::string& job_id);
  void send_running_job(const std::string& session_id, const std::string& job_id);
  bool recv_running_job();
  bool verify_management(const std::string& management, const int32_t port, const bool is_ssl);
  void send_verify_management(const std::string& management, const int32_t port, const bool is_ssl);
  bool recv_verify_management();
  bool unregister(const std::string& session);
  void send_unregister(const std::string& session);
  bool recv_unregister();
};

class launcher_serviceProcessor : public service_proxyProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<launcher_serviceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (launcher_serviceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_create_job_ex(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_create_job(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_job(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_interrupt_job(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_resume_job(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_update_job(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_remove_job(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_list_jobs(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_terminate(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_running_job(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_verify_management(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_unregister(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  launcher_serviceProcessor(::apache::thrift::stdcxx::shared_ptr<launcher_serviceIf> iface) :
    service_proxyProcessor(iface),
    iface_(iface) {
    processMap_["create_job_ex"] = &launcher_serviceProcessor::process_create_job_ex;
    processMap_["create_job"] = &launcher_serviceProcessor::process_create_job;
    processMap_["get_job"] = &launcher_serviceProcessor::process_get_job;
    processMap_["interrupt_job"] = &launcher_serviceProcessor::process_interrupt_job;
    processMap_["resume_job"] = &launcher_serviceProcessor::process_resume_job;
    processMap_["update_job"] = &launcher_serviceProcessor::process_update_job;
    processMap_["remove_job"] = &launcher_serviceProcessor::process_remove_job;
    processMap_["list_jobs"] = &launcher_serviceProcessor::process_list_jobs;
    processMap_["terminate"] = &launcher_serviceProcessor::process_terminate;
    processMap_["running_job"] = &launcher_serviceProcessor::process_running_job;
    processMap_["verify_management"] = &launcher_serviceProcessor::process_verify_management;
    processMap_["unregister"] = &launcher_serviceProcessor::process_unregister;
  }

  virtual ~launcher_serviceProcessor() {}
};

class launcher_serviceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  launcher_serviceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< launcher_serviceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< launcher_serviceIfFactory > handlerFactory_;
};

class launcher_serviceMultiface : virtual public launcher_serviceIf, public service_proxyMultiface {
 public:
  launcher_serviceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<launcher_serviceIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<apache::thrift::stdcxx::shared_ptr<launcher_serviceIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      service_proxyMultiface::add(*iter);
    }
  }
  virtual ~launcher_serviceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<launcher_serviceIf> > ifaces_;
  launcher_serviceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<launcher_serviceIf> iface) {
    service_proxyMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
  void create_job_ex(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id, const create_job_detail& create_job) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->create_job_ex(_return, session_id, job_id, create_job);
    }
    ifaces_[i]->create_job_ex(_return, session_id, job_id, create_job);
    return;
  }

  void create_job(launcher_job_detail& _return, const std::string& session_id, const create_job_detail& create_job) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->create_job(_return, session_id, create_job);
    }
    ifaces_[i]->create_job(_return, session_id, create_job);
    return;
  }

  void get_job(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_job(_return, session_id, job_id);
    }
    ifaces_[i]->get_job(_return, session_id, job_id);
    return;
  }

  bool interrupt_job(const std::string& session_id, const std::string& job_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->interrupt_job(session_id, job_id);
    }
    return ifaces_[i]->interrupt_job(session_id, job_id);
  }

  bool resume_job(const std::string& session_id, const std::string& job_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->resume_job(session_id, job_id);
    }
    return ifaces_[i]->resume_job(session_id, job_id);
  }

  bool update_job(const std::string& session_id, const std::string& job_id, const create_job_detail& job) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->update_job(session_id, job_id, job);
    }
    return ifaces_[i]->update_job(session_id, job_id, job);
  }

  bool remove_job(const std::string& session_id, const std::string& job_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->remove_job(session_id, job_id);
    }
    return ifaces_[i]->remove_job(session_id, job_id);
  }

  void list_jobs(std::vector<launcher_job_detail> & _return, const std::string& session_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->list_jobs(_return, session_id);
    }
    ifaces_[i]->list_jobs(_return, session_id);
    return;
  }

  void terminate(const std::string& session_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->terminate(session_id);
    }
    ifaces_[i]->terminate(session_id);
  }

  bool running_job(const std::string& session_id, const std::string& job_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->running_job(session_id, job_id);
    }
    return ifaces_[i]->running_job(session_id, job_id);
  }

  bool verify_management(const std::string& management, const int32_t port, const bool is_ssl) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->verify_management(management, port, is_ssl);
    }
    return ifaces_[i]->verify_management(management, port, is_ssl);
  }

  bool unregister(const std::string& session) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->unregister(session);
    }
    return ifaces_[i]->unregister(session);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class launcher_serviceConcurrentClient : virtual public launcher_serviceIf, public service_proxyConcurrentClient {
 public:
  launcher_serviceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    service_proxyConcurrentClient(prot, prot) {}
  launcher_serviceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    service_proxyConcurrentClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void create_job_ex(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id, const create_job_detail& create_job);
  int32_t send_create_job_ex(const std::string& session_id, const std::string& job_id, const create_job_detail& create_job);
  void recv_create_job_ex(launcher_job_detail& _return, const int32_t seqid);
  void create_job(launcher_job_detail& _return, const std::string& session_id, const create_job_detail& create_job);
  int32_t send_create_job(const std::string& session_id, const create_job_detail& create_job);
  void recv_create_job(launcher_job_detail& _return, const int32_t seqid);
  void get_job(launcher_job_detail& _return, const std::string& session_id, const std::string& job_id);
  int32_t send_get_job(const std::string& session_id, const std::string& job_id);
  void recv_get_job(launcher_job_detail& _return, const int32_t seqid);
  bool interrupt_job(const std::string& session_id, const std::string& job_id);
  int32_t send_interrupt_job(const std::string& session_id, const std::string& job_id);
  bool recv_interrupt_job(const int32_t seqid);
  bool resume_job(const std::string& session_id, const std::string& job_id);
  int32_t send_resume_job(const std::string& session_id, const std::string& job_id);
  bool recv_resume_job(const int32_t seqid);
  bool update_job(const std::string& session_id, const std::string& job_id, const create_job_detail& job);
  int32_t send_update_job(const std::string& session_id, const std::string& job_id, const create_job_detail& job);
  bool recv_update_job(const int32_t seqid);
  bool remove_job(const std::string& session_id, const std::string& job_id);
  int32_t send_remove_job(const std::string& session_id, const std::string& job_id);
  bool recv_remove_job(const int32_t seqid);
  void list_jobs(std::vector<launcher_job_detail> & _return, const std::string& session_id);
  int32_t send_list_jobs(const std::string& session_id);
  void recv_list_jobs(std::vector<launcher_job_detail> & _return, const int32_t seqid);
  void terminate(const std::string& session_id);
  int32_t send_terminate(const std::string& session_id);
  void recv_terminate(const int32_t seqid);
  bool running_job(const std::string& session_id, const std::string& job_id);
  int32_t send_running_job(const std::string& session_id, const std::string& job_id);
  bool recv_running_job(const int32_t seqid);
  bool verify_management(const std::string& management, const int32_t port, const bool is_ssl);
  int32_t send_verify_management(const std::string& management, const int32_t port, const bool is_ssl);
  bool recv_verify_management(const int32_t seqid);
  bool unregister(const std::string& session);
  int32_t send_unregister(const std::string& session);
  bool recv_unregister(const int32_t seqid);
};

class launcher_serviceCobClient;

class launcher_serviceCobClIf : virtual public service_proxyCobClIf {
 public:
  virtual ~launcher_serviceCobClIf() {}
  virtual void create_job_ex(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id, const create_job_detail& create_job) = 0;
  virtual void create_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const create_job_detail& create_job) = 0;
  virtual void get_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id) = 0;
  virtual void interrupt_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id) = 0;
  virtual void resume_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id) = 0;
  virtual void update_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id, const create_job_detail& job) = 0;
  virtual void remove_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id) = 0;
  virtual void list_jobs(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id) = 0;
  virtual void terminate(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id) = 0;
  virtual void running_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id) = 0;
  virtual void verify_management(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& management, const int32_t port, const bool is_ssl) = 0;
  virtual void unregister(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session) = 0;
};

class launcher_serviceCobSvIf : virtual public service_proxyCobSvIf {
 public:
  virtual ~launcher_serviceCobSvIf() {}
  virtual void create_job_ex(::apache::thrift::stdcxx::function<void(launcher_job_detail const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const std::string& job_id, const create_job_detail& create_job) = 0;
  virtual void create_job(::apache::thrift::stdcxx::function<void(launcher_job_detail const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const create_job_detail& create_job) = 0;
  virtual void get_job(::apache::thrift::stdcxx::function<void(launcher_job_detail const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const std::string& job_id) = 0;
  virtual void interrupt_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const std::string& job_id) = 0;
  virtual void resume_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const std::string& job_id) = 0;
  virtual void update_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const std::string& job_id, const create_job_detail& job) = 0;
  virtual void remove_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const std::string& job_id) = 0;
  virtual void list_jobs(::apache::thrift::stdcxx::function<void(std::vector<launcher_job_detail>  const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id) = 0;
  virtual void terminate(::apache::thrift::stdcxx::function<void()> cob, const std::string& session_id) = 0;
  virtual void running_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session_id, const std::string& job_id) = 0;
  virtual void verify_management(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, const std::string& management, const int32_t port, const bool is_ssl) = 0;
  virtual void unregister(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& session) = 0;
};

class launcher_serviceCobSvIfFactory : virtual public service_proxyCobSvIfFactory {
 public:
  typedef launcher_serviceCobSvIf Handler;

  virtual ~launcher_serviceCobSvIfFactory() {}

  virtual launcher_serviceCobSvIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(common_serviceCobSvIf* /* handler */) = 0;
};

class launcher_serviceCobSvIfSingletonFactory : virtual public launcher_serviceCobSvIfFactory {
 public:
  launcher_serviceCobSvIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<launcher_serviceCobSvIf>& iface) : iface_(iface) {}
  virtual ~launcher_serviceCobSvIfSingletonFactory() {}

  virtual launcher_serviceCobSvIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(common_serviceCobSvIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<launcher_serviceCobSvIf> iface_;
};

class launcher_serviceCobSvNull : virtual public launcher_serviceCobSvIf , virtual public service_proxyCobSvNull {
 public:
  virtual ~launcher_serviceCobSvNull() {}
  void create_job_ex(::apache::thrift::stdcxx::function<void(launcher_job_detail const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const std::string& /* job_id */, const create_job_detail& /* create_job */) {
    launcher_job_detail _return;
    return cob(_return);
  }
  void create_job(::apache::thrift::stdcxx::function<void(launcher_job_detail const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const create_job_detail& /* create_job */) {
    launcher_job_detail _return;
    return cob(_return);
  }
  void get_job(::apache::thrift::stdcxx::function<void(launcher_job_detail const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const std::string& /* job_id */) {
    launcher_job_detail _return;
    return cob(_return);
  }
  void interrupt_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return cob(_return);
  }
  void resume_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return cob(_return);
  }
  void update_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const std::string& /* job_id */, const create_job_detail& /* job */) {
    bool _return = false;
    return cob(_return);
  }
  void remove_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return cob(_return);
  }
  void list_jobs(::apache::thrift::stdcxx::function<void(std::vector<launcher_job_detail>  const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */) {
    std::vector<launcher_job_detail>  _return;
    return cob(_return);
  }
  void terminate(::apache::thrift::stdcxx::function<void()> cob, const std::string& /* session_id */) {
    return cob();
  }
  void running_job(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session_id */, const std::string& /* job_id */) {
    bool _return = false;
    return cob(_return);
  }
  void verify_management(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, const std::string& /* management */, const int32_t /* port */, const bool /* is_ssl */) {
    bool _return = false;
    return cob(_return);
  }
  void unregister(::apache::thrift::stdcxx::function<void(bool const& _return)> cob, ::apache::thrift::stdcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& /* session */) {
    bool _return = false;
    return cob(_return);
  }
};

class launcher_serviceCobClient : virtual public launcher_serviceCobClIf, public service_proxyCobClient {
 public:
  launcher_serviceCobClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::async::TAsyncChannel> channel, ::apache::thrift::protocol::TProtocolFactory* protocolFactory) :
    service_proxyCobClient(channel, protocolFactory) {}
  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::async::TAsyncChannel> getChannel() {
    return channel_;
  }
  virtual void completed__(bool /* success */) {}
  void create_job_ex(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id, const create_job_detail& create_job);
  void send_create_job_ex(const std::string& session_id, const std::string& job_id, const create_job_detail& create_job);
  void recv_create_job_ex(launcher_job_detail& _return);
  void create_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const create_job_detail& create_job);
  void send_create_job(const std::string& session_id, const create_job_detail& create_job);
  void recv_create_job(launcher_job_detail& _return);
  void get_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id);
  void send_get_job(const std::string& session_id, const std::string& job_id);
  void recv_get_job(launcher_job_detail& _return);
  void interrupt_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id);
  void send_interrupt_job(const std::string& session_id, const std::string& job_id);
  bool recv_interrupt_job();
  void resume_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id);
  void send_resume_job(const std::string& session_id, const std::string& job_id);
  bool recv_resume_job();
  void update_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id, const create_job_detail& job);
  void send_update_job(const std::string& session_id, const std::string& job_id, const create_job_detail& job);
  bool recv_update_job();
  void remove_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id);
  void send_remove_job(const std::string& session_id, const std::string& job_id);
  bool recv_remove_job();
  void list_jobs(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id);
  void send_list_jobs(const std::string& session_id);
  void recv_list_jobs(std::vector<launcher_job_detail> & _return);
  void terminate(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id);
  void send_terminate(const std::string& session_id);
  void recv_terminate();
  void running_job(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session_id, const std::string& job_id);
  void send_running_job(const std::string& session_id, const std::string& job_id);
  bool recv_running_job();
  void verify_management(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& management, const int32_t port, const bool is_ssl);
  void send_verify_management(const std::string& management, const int32_t port, const bool is_ssl);
  bool recv_verify_management();
  void unregister(::apache::thrift::stdcxx::function<void(launcher_serviceCobClient* client)> cob, const std::string& session);
  void send_unregister(const std::string& session);
  bool recv_unregister();
};

class launcher_serviceAsyncProcessor : public service_proxyAsyncProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<launcher_serviceCobSvIf> iface_;
  virtual void dispatchCall(::apache::thrift::stdcxx::function<void(bool ok)> cob, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid);
 private:
  typedef  void (launcher_serviceAsyncProcessor::*ProcessFunction)(::apache::thrift::stdcxx::function<void(bool ok)>, int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_create_job_ex(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_create_job_ex(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const launcher_job_detail& _return);
  void throw_create_job_ex(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_create_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_create_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const launcher_job_detail& _return);
  void throw_create_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_get_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_get_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const launcher_job_detail& _return);
  void throw_get_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_interrupt_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_interrupt_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const bool& _return);
  void throw_interrupt_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_resume_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_resume_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const bool& _return);
  void throw_resume_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_update_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_update_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const bool& _return);
  void throw_update_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_remove_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_remove_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const bool& _return);
  void throw_remove_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_list_jobs(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_list_jobs(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const std::vector<launcher_job_detail> & _return);
  void throw_list_jobs(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_terminate(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_terminate(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx);
  void throw_terminate(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_running_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_running_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const bool& _return);
  void throw_running_job(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_verify_management(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_verify_management(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const bool& _return);
  void throw_verify_management(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_unregister(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_unregister(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const bool& _return);
  void throw_unregister(::apache::thrift::stdcxx::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
 public:
  launcher_serviceAsyncProcessor(::apache::thrift::stdcxx::shared_ptr<launcher_serviceCobSvIf> iface) :
    service_proxyAsyncProcessor(iface),
    iface_(iface) {
    processMap_["create_job_ex"] = &launcher_serviceAsyncProcessor::process_create_job_ex;
    processMap_["create_job"] = &launcher_serviceAsyncProcessor::process_create_job;
    processMap_["get_job"] = &launcher_serviceAsyncProcessor::process_get_job;
    processMap_["interrupt_job"] = &launcher_serviceAsyncProcessor::process_interrupt_job;
    processMap_["resume_job"] = &launcher_serviceAsyncProcessor::process_resume_job;
    processMap_["update_job"] = &launcher_serviceAsyncProcessor::process_update_job;
    processMap_["remove_job"] = &launcher_serviceAsyncProcessor::process_remove_job;
    processMap_["list_jobs"] = &launcher_serviceAsyncProcessor::process_list_jobs;
    processMap_["terminate"] = &launcher_serviceAsyncProcessor::process_terminate;
    processMap_["running_job"] = &launcher_serviceAsyncProcessor::process_running_job;
    processMap_["verify_management"] = &launcher_serviceAsyncProcessor::process_verify_management;
    processMap_["unregister"] = &launcher_serviceAsyncProcessor::process_unregister;
  }

  virtual ~launcher_serviceAsyncProcessor() {}
};

class launcher_serviceAsyncProcessorFactory : public ::apache::thrift::async::TAsyncProcessorFactory {
 public:
  launcher_serviceAsyncProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< launcher_serviceCobSvIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::async::TAsyncProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< launcher_serviceCobSvIfFactory > handlerFactory_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
