/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef promise_mgmt_CONSTANTS_H
#define promise_mgmt_CONSTANTS_H

#include "promise_mgmt_types.h"

namespace mwdc { namespace ironman { namespace mgmt {

class promise_mgmtConstants {
 public:
  promise_mgmtConstants();

};

extern const promise_mgmtConstants g_promise_mgmt_constants;

}}} // namespace

#endif
