ECHO OFF

SET BOOSTZIPFILENAME=boost_1_67_0
SET BOOSTFOLDERNAME=boost-1_67
Set OLDCD=%cd%
SET PROJECTPATH="%~dp0."
cd /d %~dp0

SET BOOSTLIBS=%PROJECTPATH%\libs\%BOOSTFOLDERNAME%\x86

IF NOT EXIST %BOOSTLIBS% (
call .\build\boost-build-2012.cmd %BOOSTZIPFILENAME% %BOOSTFOLDERNAME%
)

cd /d "%OLDCD%"