/*
* Generated by 'Config.cmd' on Thu 03/08/2012 17:06:04.46-- don't edit!
*/
#ifndef _SABRECLOUD_CONFIG_H
#define _SABRECLOUD_CONFIG_H
#define CONFIG_DEBUG "n"
#define CONFIG_BUILD_DATE "Thu 03/08/2012 17:06:04.46"
#define CONFIG_HOME "C:\source\SabreCloud\C++\build"
#define CONFIG_COPYRIGHT "Copyright (C) 2006-2012 SabreCloud.  All Rights Reserved."
#define CONFIG_COPYRIGHT_WSTR L"Copyright (C) 2006-2012 SabreCloud.  All Rights Reserved."
#define CONFIG_VERSION_MAJOR "1"
#define CONFIG_VERSION_MAJOR_WSTR L"1"
#define CONFIG_VERSION_MINOR "00"
#define CONFIG_VERSION_MINOR_WSTR L"00"
#define CONFIG_BUILD_ID "111"
#define CONFIG_BUILD_ID_WSTR L"111"
#define PRODUCT_MAJOR 1 
#define PRODUCT_MINOR 00 
#define PRODUCT_BUILD 111 
#define PRODUCT_NAME_STR "SabreCloud DRaaS Utilities"
#define PRODUCT_NAME_WSTR L"SabreCloud DRaaS Utilities"
#define PRODUCT_FULLNAME_STR "SabreCloud® DRaaS Utilities"
#define PRODUCT_FULLNAME_WSTR L"SabreCloud® DRaaS Utilities"
#define PRODUCT_SHORTNAME_STR "SabreCloud"
#define PRODUCT_SHORTNAME_WSTR L"SabreCloud"
#define PRODUCT_MS_VERSION_STR   "1,00, 0, 111" 
#define PRODUCT_VENDOR_STR "SabreCloud"
#define PRODUCT_VENDOR_WSTR L"SabreCloud"
#endif /* ifndef _SABRECLOUD_CONFIG_H */
